- hosts: openvpn
  become: true
  become_user: root
  tasks:
    - name: Start OpenVPN connection
      service:
        name: openvpn@szappanosauto-client
        state: started
 
    - name: Test reachability to 192.168.60.15
      ansible.netcommon.net_ping:
        dest: 192.168.60.15
        count: 20
 
    - name: Stopped OpenVPN connection
      service:
        name: openvpn@szappanosauto-client
        state: stopped
 
