- hosts: openvpn
  become: true
  become_user: root
  tasks:
    - name: Start OpenVPN connection
      service:
        name: openvpn@szappanosauto-client
        state: started
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300

- hosts: servers
  tasks:
    - action: ping

- hosts: openvpn
  become: true
  become_user: root
  tasks:    
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Stopped OpenVPN connection
      service:
        name: openvpn@szappanosauto-client
        state: stopped
