- hosts: openvpn
  become: true
  become_user: root
  tasks:
    - name: Start OpenVPN connection
      service:
        name: openvpn@szappanosauto-client
        state: started
 
    - name: Example from an Ansible Playbook
      ansible.builtin.ping:
 
    - name: Stopped OpenVPN connection
      service:
        name: openvpn@szappanosauto-client
        state: stopped
 
